build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
labels:
  maintainer: "hanwg (https://github.com/hanwg)"
  org.opencontainers.image.title: "Home Assistant Addon: Telegram Bot API"
  org.opencontainers.image.description: "Docker image for Telegram Bot API. Built for Home Assistant as an addon."
  org.opencontainers.image.source: "https://github.com/hanwg/telegram-bot-api"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.authors: "hanwg (https://github.com/hanwg)"
  org.opencontainers.image.url: "https://github.com/hanwg/telegram-bot-api"
  org.opencontainers.image.documentation: "https://github.com/hanwg/telegram-bot-api/blob/main/README.md"
args:
  BUILD_VERSION: 9.3
